### ISSUE TITLE
problem with redis

### ISSUE THREAD

**Issue by ilseva** [google/moodle-on-gcp#20]
I'm triyng to use the nginx image with redis, but I receive this error when after I logged in

`The session caches can not be in the session store when enable_read_only_sessions is enabled. Please map all session mode caches to be outside of the default session store before enabling this features. Found these definitions in the session: core/calendar_categories, core/coursecat`

whats is wrong?
thanks.

**Comment by ernani** [comment]
Apparently this is an implementation decision from Moodle core, this error happens with a condition met in the given description here:

https://tracker.moodle.org/browse/MDL-78224

Apparently when you set the session cache debug it will run into this error.

I'd propose a fix but still waiting for someone to reply.

**Comment by ernani** [comment]
The logic seems off in this file: https://fossies.org/linux/moodle/lib/classes/session/manager.php in lines 126-127 and we don't touch Moodle core when deploying it, so don't enable debug for now and you should be fine.
